function displayFeatures()

    if(exist('ComputeFeature') ~=2)
        error('Please add the ACA scripts (https://github.com/alexanderlerch/ACA-Code) to your path!');
    end

    cFeatureNames = char('SpectralCentroid',...
    'SpectralCrest',...
    'SpectralDecrease',...
    'SpectralFlatness',...
    'SpectralFlux',...
    'SpectralKurtosis',...
    'SpectralMfccs',...
    'SpectralPitchChroma',...
    'SpectralRolloff',...
    'SpectralSkewness',...
    'SpectralSlope',...
    'SpectralSpread',...
    'SpectralTonalPowerRatio',...
    'TimeAcfCoeff',...
    'TimeMaxAcf',...
    'TimePeakEnvelope',...
    'TimePredictivityRatio',...
    'TimeRms',...
    'TimeStd',...
    'TimeZeroCrossingRate');

    % read sample data
    [cPath, cName]  = fileparts(mfilename('fullpath'));
    [x,fs]  = audioread([cPath '/../audio/sax_example.wav']);
    t       = linspace(0,(length(x)-1)/fs,length(x));
    x       = x/max(abs(x));
    [X,f,tf]= spectrogram(x, hann(2048,'periodic'),1024,2048,fs);
 
    for (i=1:size(cFeatureNames,1))
        cOutputFilePath = [cPath '/../graph/' strrep(cName, 'display', '') deblank(cFeatureNames(i,:))];
        hFigureHandle   = generateFigure(10.8,6);
 
        [v, tv]         = ComputeFeature (deblank(cFeatureNames(i,:)), x, fs);

        
        subplot(211), 
        imagesc(tf,f(1:floor(end/2))/1000,20*log10(abs(X(1:floor(end/2),:))))
        axis xy;
        ylabel(['f [kHz]'])
        
        subplot(212)
        [AX,H2,H1] = plotyy(t,x, tv,v);
        set(AX(1),'XLim', [0 max(t(end),tv(end))], 'YLim', [-1 1])
        set(AX(2),'XLim', [0 max(t(end),tv(end))], 'YLim', [min(min(v)) max(max(v))])        
        xlabel('t [s]')
        ylabel(AX(1),'x(i)')
        ylabel(AX(2),'v(n)')

        printFigure(hFigureHandle, cOutputFilePath)
    end
end